# Use postgres/example user/password credentials
version: '3.9'

services:

  app:
    build: .
    ports:
      - 3000:3000 
    command: yarn dev
    links:
      - "db"
    depends_on:
      - db
    networks:
      - frontend
    
 
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: waproject
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - frontend

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
volumes:
  postgres:
  app_path: